#set heading(numbering: "1.")
#show link: underline

#align(center, text(30pt)[*False King*])
#align(center, text(20pt)[By Elliot McNeil])

#outline()
#pagebreak()

#include("intro.typ")
#pagebreak()
#include("concept.typ")
#pagebreak()
#include("platforms.typ")
#pagebreak()
#include("tools.typ")
#pagebreak()
#include("visuals.typ")
#pagebreak()
#include("audio.typ")
#pagebreak()
#include("input.typ")
#pagebreak()
#include("ui.typ")
#pagebreak()
#include("data.typ")
#pagebreak()
#include("story.typ")
#pagebreak()
#include("timeline.typ")
